LOCK TABLES JHI_USER_AUTHORITY WRITE, JHI_AUTHORITY WRITE;
ALTER TABLE JHI_USER_AUTHORITY DROP FOREIGN KEY fk_authority_name;
ALTER TABLE JHI_USER_AUTHORITY DROP INDEX fk_authority_name;
ALTER TABLE JHI_USER_AUTHORITY CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE JHI_AUTHORITY CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE JHI_USER_AUTHORITY ADD CONSTRAINT `fk_authority_name` FOREIGN KEY (`authority_name`) REFERENCES `JHI_AUTHORITY` (`name`);

UNLOCK TABLES;

ALTER TABLE JHI_PERSISTENT_AUDIT_EVENT CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE JHI_PERSISTENT_AUDIT_EVT_DATA CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE JHI_PERSISTENT_TOKEN CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE JHI_USER CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;


ALTER TABLE ALIAS CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE MEETING CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE MEETING_PARTNER CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE MEETING_TAG CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE PARTNER CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE SUBMITTER CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE TAG CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE USER_ALIAS CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;



ALTER TABLE DATABASECHANGELOG CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE DATABASECHANGELOGLOCK CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;