server:
    port: 8080

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    datasource:
        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/lobbycal
        databaseName: 
        serverName: 
        username: lobbycal
        password: lobbycal
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            
            
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: elasticsearch/log
                  data: elasticsearch/data
    thymeleaf:
        mode: XHTML
        cache: true
    jackson: 
        serialization:
            INDENT_OUTPUT: true

metrics:
    jmx.enabled: false
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: lobbycal

http:
    cache:
        timeToLiveInDays: 1
        
        
mail:
    host: yourhost
    port: 465
    username: 
    password: 
    protocol: 
    tls: false
    auth: true
    from: 
    
    
catchall:
        mail:
                host: 
                username: 
                password: 
                port: 
                nossl: 
                folder: INBOX

