spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  messages:
    basename: classpath:/i18n/messages
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: XHTML
security:
  basic:
    enabled: false
jhipster:
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
  cors:
    allowed-origins: '*'
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: '*'
    exposed-headers: null
    allow-credentials: true
    max-age: 1800
  mail:
    from: lobbycal@lobbycal
  security:
    rememberme:
      key: 12172397439723954192854983265491854
  swagger:
    title: lobbycal API
    description: lobbycal application programmer interface
    termsOfServiceUrl: https://github.com/TransparencyInternationalEU/lobbycal
    contact: Transparency International EU
    license: CC0
    licenseUrl: https://creativecommons.org/publicdomain/zero/1.0/
mail:
  host: addmailhosthere
  port: 465
  username: u
  password: p
  protocol: smtp
  tls: false
  auth: true
  from: senderusername
catchall:
  mail:
    host: catchallmailhost
    username: uname
    password: p
    port: 143
    nossl: true
    folder: INBOX
    interval: 20000
lobbycal:
  meetings:
    delivery: past
    fullListURL: http://yourserverwithworpressorstandaloneclient/all
    reminder:
      noNewMeeting:
        sinceLastDays: 30
  lobbycloud:
    active: false
    sendTo: info@somone
    triggerUrl: http://localhost:8080/lobbycloud
    tag: null